name: Make TWRP Device

on:
  workflow_dispatch:
    inputs:
      IMG_URL:    
        description: 'URL of your image'
        required: true
        default: ''

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-22.04

    steps:
    - name: Check Out
      uses: actions/checkout@main
    - name: Prepare the environment
      run: |
        sudo apt update && apt install -y \
          python3 python3-pip python-is-python3 cpio wget
        pip install twrpdtgen
    - name: Download boot or recovery img
      run: |
        aria2c "${{ github.event.inputs.IMG_URL }}"
        ls -alh *.img
    - name: Start build
      run: |
        python -m twrpdtgen -o dt/ *.img
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        path: dt/
        name: TWRP_Device_Tree-${{ github.run_id }}
